name: env-eda
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - ipykernel # pre-requisite for treating env as jupyter kernel
    - pandas
    - openpyxl # pre-requisite for pandas.read_excel()
    - bokeh