name: env-prophet
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - ipykernel # pre-requisite for treating env as jupyter kernel
    - pandas
    - prophet
    - scikit-learn
    - openpyxl # pre-requisite for pandas.read_excel()