name: env-hackathon23_somnolence_ankit
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - ipykernel # pre-requisite for treating env as jupyter kernel
    - pandas
    - lxml # pre-requisite for pandas.read_html()
    - openpyxl # pre-requisite for pandas.read_html()
